import logging
from pathlib import Path

from prusa.connect.client.gcode import parse_gcode_header

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

# Path to the reference data
DATA_DIR = Path(__file__).parent / "data"


def test_parse_bgcode_real_file():
    """Verify parsing of the real benchy .bgcode file."""
    bgcode_path = DATA_DIR / "benchyrules_pla_14m.bgcode"
    assert bgcode_path.exists()

    metadata = parse_gcode_header(bgcode_path)
    logger.info(metadata)

    # Expected values for the provided benchy file
    assert metadata.printer_model == "MK4S"
    assert metadata.nozzle_diameter == 0.4
    assert metadata.layer_height == 0.25
    assert metadata.filament_type == "PLA"
    assert metadata.fill_density == "10%"
    assert metadata.bed_temperature == 55
    assert metadata.temperature == 220
    assert metadata.estimated_time_mode == "normal"
    assert metadata.gcode_type == "binary"
    assert metadata.producer is not None
    assert "PrusaSlicer" in metadata.producer

    assert metadata.estimated_time is not None
    assert 800 < metadata.estimated_time < 900


def test_parse_gcode_real_file():
    """Verify parsing of the real benchy .gcode file (ASCII conversion)."""
    gcode_path = DATA_DIR / "benchyrules_pla_14m.gcode"
    assert gcode_path.exists()

    metadata = parse_gcode_header(gcode_path)
    logger.info(metadata)

    assert metadata.printer_model == "MK4S"
    assert metadata.nozzle_diameter == 0.4
    assert metadata.layer_height == 0.25
    assert metadata.filament_type == "PLA"
    assert metadata.fill_density == "10%"
    assert metadata.bed_temperature == 55
    assert metadata.temperature == 220
    assert metadata.estimated_time_mode == "normal"
    assert metadata.gcode_type == "ascii"
    assert metadata.producer is not None
    assert "PrusaSlicer" in metadata.producer

    assert metadata.estimated_time is not None
    assert 800 < metadata.estimated_time < 900


def test_parse_gcode_legacy_compatibility(tmp_path):
    """Ensure older ASCII formats with h/m/s and stealth mode still work."""
    gcode_content = """
; printer_model = MK3S
; layer_height = 0.15
; nozzle_diameter = 0.4
; filament used [mm] = 500.0
; estimated printing time (stealth mode) = 2h 15m 30s
; filament_type = PETG
; fill_density = 20%
; bed_temperature = 80
; temperature = 240
; generated by PrusaSlicer 2.6.0
"""
    p = tmp_path / "legacy.gcode"
    p.write_text(gcode_content)

    metadata = parse_gcode_header(p)
    assert metadata.printer_model == "MK3S"
    assert metadata.estimated_time == (2 * 3600) + (15 * 60) + 30
    assert metadata.estimated_time_mode == "stealth"
    assert metadata.filament_type == "PETG"
    assert metadata.fill_density == "20%"
    assert metadata.bed_temperature == 80
    assert metadata.temperature == 240
    assert metadata.gcode_type == "ascii"
    assert metadata.producer == "PrusaSlicer 2.6.0"
